import resourceBase = require("./gen/stories_base");
resourceBase.comment = "A _story_ represents an activity associated with an object in the Asana\nsystem. Stories are generated by the system whenever users take actions such\nas creating or assigning tasks, or moving tasks between projects. _Comments_\nare also a form of user-generated story.\n";
resourceBase.properties = [
  {
    "name": "gid",
    "type": "Gid",
    "example_values": [
      "\"1234\""
    ],
    "comment": "Globally unique ID of the story.\n"
  },
  {
    "name": "resource_type",
    "type": "Enum",
    "comment": "The resource type of this resource. The value for this resource is always `story`.\n",
    "example_values": [
      "\"story\""
    ],
    "values": [
      {
        "name": "story",
        "comment": "A story resource type."
      }
    ]
  },
  {
    "name": "resource_subtype",
    "type": "Enum",
    "comment": "The type of story. This provides fine-grained information about what triggered the story's creation. There are many story subtypes, so inspect the data returned from Asana's API to find the value for your use case.\n",
    "example_values": [
      "\"comment_added\"",
      "\"description_changed\"",
      "\"liked\"",
      "..."
    ]
  },
  {
    "name": "created_at",
    "type": "String",
    "example_values": [
      "'2012-02-22T02:06:58.147Z'"
    ],
    "comment": "The time at which this story was created.\n"
  },
  {
    "name": "created_by",
    "type": "User",
    "example_values": [
      "{ id: 12345, gid: \"12345\", resource_type: \"user\", name: 'Tim Bizarro' }",
      "null"
    ],
    "comment": "The user who created the story.\n"
  },
  {
    "name": "liked",
    "type": "Boolean",
    "example_values": [
      "false"
    ],
    "comment": "True if the story is liked by the authorized user, false if not.\n",
  },
  {
    "name": "likes",
    "type": "Array",
    "example_values": [
      "[ { id: 1123, gid: \"1123\", resource_type: \"user\", name: 'Mittens' }, ... ]"
    ],
    "comment": "Array of users who have liked this story.\n",
  },
  {
    "name": "num_likes",
    "type": "Integer",
    "example_values": [
      "5"
    ],
    "comment": "The number of users who have liked this story.\n",
  },
  {	
    "name": "text",	
    "type": "String",	
    "example_values": [	
      "'marked today'"	
    ],	
    "comment": "Human-readable text for the story or comment. This will not include the\nname of the creator.\n",	
  },
  {
    "name": "html_text",
    "type": "String",
    "example_values": [
      "'&lt;body&gt;Get whatever &lt;a href='https://app.asana.com/0/1123/list'&gt;Sashimi&lt;/a&gt; has.&lt;/body&gt;'"
    ],
    "comment": "[Opt In](https://asana.com/developers/documentation/getting-started/input-output-options). HTML formatted text for a comment.\n"
  },
  {
    "name": "target",
    "type": "Task",
    "example_values": [
      "{ id: 1234, gid: \"1234\", name: 'Bug task' }"
    ],
    "comment": "The object this story is associated with. Currently may only be a task.\n"
  },
  {
    "name": "is_pinned",
    "type": "Boolean",
    "example_values": [
      "false"
    ],
    "comment": "Whether the story is pinned on the target.\n",
  },
  {
    "name": "is_edited",
    "type": "Boolean",
    "example_values": [
      "false"
    ],
    "comment": "Whether the text of the story has been edited after creation.\n",
  },
  {
    "name": "source",
    "type": "Enum",
    "example_values": [
      "'web'"
    ],
    "values": [
      {
        "name": "web",
        "comment": "Via the Asana web app."
      },
      {
        "name": "email",
        "comment": "Via email."
      },
      {
        "name": "mobile",
        "comment": "Via the Asana mobile app."
      },
      {
        "name": "api",
        "comment": "Via the Asana API."
      },
      {
        "name": "unknown",
        "comment": "Unknown or unrecorded."
      }
    ],
    "comment": "The component of the Asana product the user used to create the story.\n"
  },
]

export = resourceBase;