# Cache node_modules and typings for future runs. This does make the builds
# sometimes fail because of a bad cache but usually this is a huge test
# performance win.
cache:
  directories:
    - node_modules
    - typings
# Set up environment variables for tests
env:
  global:
    # Use a better mocha reporter for Travis
    - MOCHA_REPORTER=spec
# Use the Travis Docker build system which is faster
sudo: false
# Specify to use node
language: node_js
# Specify the node versions to run on
node_js:
  - "10.16.0"
before_deploy:
  - npm run web
# Push to gh-pages
# TODO: Re-enable automatic push to gh-pages
# after_success:
#  - git config --global user.email "git@asana.com"
#  - git config --global user.name "Asana"
#  # only publish to gh-pages from the master branch.
#  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gulp gh-pages
