cache:
  directories:
    - node_modules
    - typings
language: node_js
node_js:
  - '0.10'
sudo: false
# Set up github token for higher tsd rate-limits
before_install:
- openssl aes-256-cbc -K $encrypted_d04ead2b6c5a_key -iv $encrypted_d04ead2b6c5a_iv
  -in .tsdrc.enc -out .tsdrc -d
after_success:
  - git config --global user.email "git@asana.com"
  - git config --global user.name "Asana"
  # only publish to gh-pages from the master branch.
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gulp gh-pages
env:
  global:
    # ASANA_GITHUB_TOKEN = ...
    - secure: "DAwDB8TF1HEzqBzVHDR88kAOXOzcHx0AeFaazofh6OGDbxGuIbNWOgv8xXb4F1GScBX26KXwQPcskvP/qWJ49jW91iePcsTAIDtNLgg7UGj/L9eSeKyoHb93l7tah02zZzHjn4vCKjQfMeLAXdYbZf2VX5PM2cRdXlLx24WaqBY="